site_name: AndroidTamer-KB
docs_dir: Documents
site_description: KnowledgeBase for Android Tamer
site_author: AndroidTamer Team
site_dir: site
#theme: readthedocs
markdown_extensions:
  - markdown_newtab
  - oembed
  - markdown_checklist.extension
#include_next_prev: false
copyright: (c) Android Tamer Team
site_favicon: favicon.ico
theme: 'tamerdocs'
#theme_dir: mkdocs-reloaded/mkdocs-reloaded
repo_url: https://github.com/AndroidTamer
extra:
  search: false
  twitter: https://www.twitter.com/AndroidTamer
  facebook: https://www.facebook.com/AndroidTamer
  irc: https://webchat.freenode.net/?url=irc://irc.freenode.net/androidtamer